//
//  NetworkTransaction+cURL.swift
//  SwiftyDebug
//
//  Created by Omar Hariri on 06/03/2026.
//

import Foundation

extension NetworkTransaction {

    /// Headers auto-generated by cURL — including them breaks replay.
    private static let skipHeaders: Set<String> = [
        "content-length",
        "host",
        "transfer-encoding",
        "connection",
        "accept-encoding",
    ]

    /// Build a valid cURL command that reproduces the original request.
    ///
    /// Two intentional fixes applied:
    /// 1. Content-Type: Some iOS SDKs set `x-www-form-urlencoded` but send JSON bodies.
    ///    URLSession handles this, but cURL/Postman reject the mismatch → fix to `application/json`.
    /// 2. Params expansion: Multi-query requests with `requests[].params` URL-encoded strings
    ///    are expanded into individual JSON keys for full API compatibility.
    func cURLDescription(cachedRequestData: Data? = nil) -> String {
        var parts = [String]()

        // 1. Method
        parts.append("curl -X \((method ?? "GET").uppercased())")

        // 2. URL
        parts.append(shellQuote(url?.absoluteString ?? ""))

        // 3. Prepare body
        let bodyData: Data? = cachedRequestData ?? self.requestData
        let bodyIsJSON = bodyData.flatMap { Self.looksLikeJSON($0) } ?? false

        // Try to expand URL-encoded params in JSON body (Algolia multi-query, etc.)
        // Falls back to original body string if no expansion needed.
        var bodyString: String? = nil
        if bodyIsJSON, let data = bodyData {
            bodyString = Self.expandParamsInJSON(data)
        }
        if bodyString == nil, let data = bodyData, !data.isEmpty {
            bodyString = String(data: data, encoding: .utf8)
        }

        // 4. Headers
        if let headers = requestHeaderFields as? [String: Any] {
            for key in headers.keys.sorted() {
                if Self.skipHeaders.contains(key.lowercased()) { continue }

                // Fix Content-Type when body is JSON but header says otherwise
                if bodyIsJSON && key.lowercased() == "content-type" {
                    let value = "\(headers[key] ?? "")"
                    if !value.lowercased().contains("application/json") {
                        parts.append("-H \(shellQuote("Content-Type: application/json"))")
                        continue
                    }
                }

                parts.append("-H \(shellQuote("\(key): \(headers[key] ?? "")"))")
            }
        }

        // 5. Body
        if let body = bodyString, !body.isEmpty {
            parts.append("--data-raw \(shellQuote(body))")
        } else if let data = bodyData, !data.isEmpty {
            let size = data.count
            let sizeStr = size < 1024 ? "\(size) bytes"
                : size < 1024 * 1024 ? String(format: "%.1f KB", Double(size) / 1024.0)
                : String(format: "%.1f MB", Double(size) / (1024.0 * 1024.0))
            parts.append("# Binary body: \(sizeStr) (not included)")
        }

        return parts.joined(separator: " \\\n  ")
    }

    // MARK: - JSON Params Expansion

    /// Expands `requests[].params` URL-encoded strings into individual JSON keys.
    ///
    /// Before: `{"requests":[{"params":"query=foo&page=0","indexName":"x"}]}`
    /// After:  `{"requests":[{"indexName":"x","page":0,"query":"foo"}]}`
    ///
    /// Returns nil if no expansion was needed (no `params` strings found).
    private static func expandParamsInJSON(_ data: Data) -> String? {
        guard var json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let requests = json["requests"] as? [[String: Any]] else {
            return nil
        }

        guard requests.contains(where: { $0["params"] is String }) else { return nil }

        var expanded = [[String: Any]]()
        for var request in requests {
            if let params = request["params"] as? String {
                request.removeValue(forKey: "params")
                let parsed = parseURLEncoded(params)
                for (key, value) in parsed where request[key] == nil {
                    request[key] = value
                }
            }
            expanded.append(request)
        }

        json["requests"] = expanded

        var options: JSONSerialization.WritingOptions = [.sortedKeys, .withoutEscapingSlashes]
        guard let newData = try? JSONSerialization.data(withJSONObject: json, options: options),
              let result = String(data: newData, encoding: .utf8) else {
            return nil
        }

        return result
    }

    /// Parse a URL-encoded query string into typed key-value pairs.
    private static func parseURLEncoded(_ string: String) -> [String: Any] {
        var result = [String: Any]()

        for pair in string.split(separator: "&", omittingEmptySubsequences: false) {
            let kv = pair.split(separator: "=", maxSplits: 1, omittingEmptySubsequences: false)
            guard let rawKey = kv.first, !rawKey.isEmpty else { continue }

            let key = String(rawKey).removingPercentEncoding ?? String(rawKey)
            let rawValue = kv.count > 1 ? String(kv[1]) : ""
            let decoded = rawValue.removingPercentEncoding ?? rawValue

            result[key] = typedValue(decoded)
        }

        return result
    }

    /// Convert a decoded string value to the most fitting JSON type.
    private static func typedValue(_ string: String) -> Any {
        if string.isEmpty { return "" }

        // Booleans
        if string == "true" { return true }
        if string == "false" { return false }

        // Integer (page, hitsPerPage, etc.)
        if let n = Int(string) { return n }

        // JSON array/object (e.g. aroundPrecision=[{"from":0,"value":20000}])
        if string.hasPrefix("[") || string.hasPrefix("{"),
           let data = string.data(using: .utf8),
           let obj = try? JSONSerialization.jsonObject(with: data) {
            return obj
        }

        // Comma-separated list → array (unless it looks like a lat,lng coordinate)
        if string.contains(","), !isCoordinate(string) {
            return string.split(separator: ",").map { String($0) }
        }

        return string
    }

    /// "25.3738,49.5821" → coordinate (exactly two decimal numbers).
    private static func isCoordinate(_ string: String) -> Bool {
        let parts = string.split(separator: ",")
        guard parts.count == 2 else { return false }
        return Double(parts[0]) != nil && Double(parts[1]) != nil
    }

    // MARK: - Helpers

    /// Quick check: does the data start with `{` or `[` (after whitespace)?
    private static func looksLikeJSON(_ data: Data) -> Bool {
        for byte in data {
            if byte == 0x20 || byte == 0x09 || byte == 0x0A || byte == 0x0D { continue }
            return byte == UInt8(ascii: "{") || byte == UInt8(ascii: "[")
        }
        return false
    }

    /// Shell-quote using single quotes (POSIX standard).
    private func shellQuote(_ string: String) -> String {
        return "'\(string.replacingOccurrences(of: "'", with: "'\\''"))'"
    }
}
